# Generated by Django 2.0.5 on 2018-12-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='login',
            new_name='username',
        ),
        migrations.AddField(
            model_name='sessions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Users'),
        ),
    ]
