# Generated by Django 2.0.5 on 2020-01-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181223_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
