# Generated by Django 2.0.5 on 2018-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('social_status', models.CharField(max_length=50)),
                ('complaint', models.TextField(max_length=200)),
                ('history', models.TextField(max_length=200)),
            ],
        ),
    ]
