# Generated by Django 2.0.5 on 2018-10-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patients',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
