# Generated by Django 2.0.5 on 2018-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('position', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('work_experience', models.IntegerField(default=0)),
                ('scientific_degree', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
