# Generated by Django 2.0.5 on 2018-10-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffer',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffer',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='specialization',
            field=models.CharField(default='', max_length=50),
        ),
    ]
