# Generated by Django 2.0.5 on 2020-01-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_auto_20200101_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='staffer',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
