# Generated by Django 2.0.5 on 2020-01-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_auto_20200101_1215'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staffer',
            managers=[
            ],
        ),
    ]
