# Generated by Django 2.0.5 on 2020-01-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='occupation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
