# Generated by Django 2.0.5 on 2020-01-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0012_auto_20200104_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
