# Generated by Django 2.0.5 on 2020-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0013_staffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffer',
            name='img',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
